    ['tltypes'] = {
        ['name'] = 'Acura TL Type-S',
        ['brand'] = 'aston',
        ['model'] = 'tltypes',
        ['price'] = 24000,
        ['category'] = 'aston',
        ['hash'] = `tltypes`,
        ['shop'] = 'pdm',
    },
    ['amdbx'] = {
        ['name'] = 'Aston Martin DBX Carbon Edition',
        ['brand'] = 'aston',
        ['model'] = 'amdbx',
        ['price'] = 24000,
        ['category'] = 'aston',
        ['hash'] = `amdbx`,
        ['shop'] = 'pdm',
      },
    ['ast'] = {
        ['name'] = '2013 Aston Martin Vanquish',
        ['brand'] = 'aston',
        ['model'] = 'ast',
        ['price'] = 24000,
        ['category'] = 'aston',
        ['hash'] = `ast`,
		['shop'] = 'pdm',
    },
    ['80B4'] = {
        ['name'] = '1995 Audi Cabriolet',
        ['brand'] = 'audi',
        ['model'] = '80B4',
        ['price'] = 24000,
        ['category'] = 'audi',
        ['hash'] = `80B4`,
		['shop'] = 'pdm',
    },
    ['audquattros'] = {
        ['name'] = '1983 Audi Quattro Sport',
        ['brand'] = 'audi',
        ['model'] = 'audquattros',
        ['price'] = 24000,
        ['category'] = 'audi',
        ['hash'] = `audquattros`,
		['shop'] = 'pdm',
    },
    ['aaq4'] = {
        ['name'] = '2017 Audi A4 Quattro ABT',
        ['brand'] = 'audi',
        ['model'] = 'aaq4',
        ['price'] = 24000,
        ['category'] = 'audi',
        ['hash'] = `aaq4`,
        ['shop'] = 'pdm',
    },
    ['q820'] = {
        ['name'] = '2020 Audi Q8 50TDI',
        ['brand'] = 'audi',
        ['model'] = 'q820',
        ['price'] = 15000,
        ['category'] = 'audi',
        ['hash'] = `q820`,
        ['shop'] = 'pdm',
    },
    ['r8ppi'] = {
        ['name'] = '2013 Audi R8 V10',
        ['brand'] = 'audi',
        ['model'] = 'r8ppi',
        ['price'] = 19000,
        ['category'] = 'audi',
        ['hash'] = `r8ppi`,
        ['shop'] = 'pdm',
    },
    ['r820'] = {
        ['name'] = '2020 Audi R8',
        ['brand'] = 'audi',
        ['model'] = 'r820',
        ['price'] = 55000,
        ['category'] = 'audi',
        ['hash'] = `r820`,
        ['shop'] = 'pdm',
    },
    ['rs6'] = {
        ['name'] = '2016 Audi RS6 C7',
        ['brand'] = 'audi',
        ['model'] = 'rs6',
        ['price'] = 35000,
        ['category'] = 'audi',
        ['hash'] = `rs6`,
        ['shop'] = 'pdm',
    },
    ['rs72020'] = {
        ['name'] = '2020 Audi RS7',
        ['brand'] = 'audi',
        ['model'] = 'rs72020',
        ['price'] = 28000,
        ['category'] = 'audi',
        ['hash'] = `rs72020`,
        ['shop'] = 'pdm',
    },
    ['s8d2'] = {
        ['name'] = '1998 Audi S8',
        ['brand'] = 'audi',
        ['model'] = 's8d2',
        ['price'] = 28000,
        ['category'] = 'audi',
        ['hash'] = `s8d2`,
        ['shop'] = 'pdm',
    },
    ['sq72016'] = {
        ['name'] = '2016 Audi SQ7',
        ['brand'] = 'audi',
        ['model'] = 'sq72016',
        ['price'] = 30000,
        ['category'] = 'audi',
        ['hash'] = `sq72016`,
        ['shop'] = 'pdm',
    },
    ['ttrs'] = {
        ['name'] = '2010 Audi TT RS',
        ['brand'] = 'audi',
        ['model'] = 'ttrs',
        ['price'] = 125000,
        ['category'] = 'audi',
        ['hash'] = `ttrs`,
        ['shop'] = 'pdm',
    },
    ['bbentayga'] = {
        ['name'] = 'Bentley Bentayga',
        ['brand'] = 'bentley',
        ['model'] = 'bbentayga',
        ['price'] = 20000,
        ['category'] = 'bentley',
        ['hash'] = `bbentayga`,
        ['shop'] = 'pdm',
    },
    ['cgts'] = {
        ['name'] = '2020 Bentley Continental GT Convertible',
        ['brand'] = 'bentley',
        ['model'] = 'cgts',
        ['price'] = 30000,
        ['category'] = 'bentley',
        ['hash'] = `cgts`,
        ['shop'] = 'pdm',
    },
    ['760li04'] = {
        ['name'] = '2004 BMW 760Li Individual E66/PFL',
        ['brand'] = 'bmw',
        ['model'] = '760li04',
        ['price'] = 40000,
        ['category'] = 'bmw',
        ['hash'] = `760li04`,
        ['shop'] = 'pdm',
    },
    ['e34'] = {
        ['name'] = '1995 BMW M5 E34',
        ['brand'] = 'bmw',
        ['model'] = 'e34',
        ['price'] = 40000,
        ['category'] = 'bmw',
        ['hash'] = `e34`,
        ['shop'] = 'pdm',
    },
    ['m2'] = {
        ['name'] = '2016 BMW M2',
        ['brand'] = 'bmw',
        ['model'] = 'm2',
        ['price'] = 12500,
        ['category'] = 'bmw',
        ['hash'] = `m2`,
        ['shop'] = 'pdm',
    },
    ['m3e36'] = {
        ['name'] = '1997 BMW M3 E36',
        ['brand'] = 'bmw',
        ['model'] = 'm3e36',
        ['price'] = 18000,
        ['category'] = 'bmw',
        ['hash'] = `m3e36`,
        ['shop'] = 'pdm',
    },
    ['m3e92'] = {
        ['name'] = '2008 BMW M3 e92',
        ['brand'] = 'bmw',
        ['model'] = 'm3e92',
        ['price'] = 20000,
        ['category'] = 'bmw',
        ['hash'] = `m3e92`,
        ['shop'] = 'pdm',
    },
    ['m3f80'] = {
        ['name'] = '2015 BMW M3 F80',
        ['brand'] = 'bmw',
        ['model'] = 'm3f80',
        ['price'] = 25000,
        ['category'] = 'bmw',
        ['hash'] = `m3f80`,
        ['shop'] = 'pdm',
    },
    ['m4f82'] = {
        ['name'] = '2015 BMW M4 F82',
        ['brand'] = 'bmw',
        ['model'] = 'm4f82',
        ['price'] = 11500,
        ['category'] = 'bmw',
        ['hash'] = `m4f82`,
        ['shop'] = 'pdm',
    },
    ['m6f13'] = {
        ['name'] = 'BMW M6 F13 Shadow Line',
        ['brand'] = 'bmw',
        ['model'] = 'm6f13',
        ['price'] = 16000,
        ['category'] = 'bmw',
        ['hash'] = `m6f13`,
        ['shop'] = 'pdm',
    },
    ['z419'] = {
        ['name'] = '2019 BMW Z4 M40i',
        ['brand'] = 'bmw',
        ['model'] = 'z419',
        ['price'] = 14000,
        ['category'] = 'bmw',
        ['hash'] = `z419`,
        ['shop'] = 'pdm',
    },
    ['bolide'] = {
        ['name'] = '2020 Bugatti Bolide',
        ['brand'] = 'bugatti',
        ['model'] = 'bolide',
        ['price'] = 12500,
        ['category'] = 'bugatti',
        ['hash'] = `bolide`,
        ['shop'] = 'pdm',
    },
    ['cats'] = {
        ['name'] = '2016 Cadillac ATS-V Coupe',
        ['brand'] = 'cadillac',
        ['model'] = 'cats',
        ['price'] = 7200,
        ['category'] = 'cadillac',
        ['hash'] = `cats`,
        ['shop'] = 'pdm',
    },
    ['cesc21'] = {
        ['name'] = '2021 Cadillac Escalade',
        ['brand'] = 'cadillac',
        ['model'] = 'cesc21',
        ['price'] = 8000,
        ['category'] = 'cadillac',
        ['hash'] = `cesc21`,
        ['shop'] = 'pdm',
    },
    ['09tahoe'] = {
        ['name'] = '2009 Chevrolet Tahoe',
        ['brand'] = 'chevrolet',
        ['model'] = '09tahoe',
        ['price'] = 18000,
        ['category'] = 'cadillac',
        ['hash'] = `09tahoe`,
        ['shop'] = 'pdm',
    },
    ['15tahoe'] = {
        ['name'] = '2015 Chevrolet Tahoe',
        ['brand'] = 'chevrolet',
        ['model'] = '15tahoe',
        ['price'] = 10000,
        ['category'] = 'super',
        ['hash'] = `15tahoe`,
        ['shop'] = 'pdm',
    },
    ['2020ss'] = {
        ['name'] = '2020 Chevrolet Camaro SS',
        ['brand'] = 'chevrolet',
        ['model'] = '2020ss',
        ['price'] = 10000,
        ['category'] = 'chevrolet',
        ['hash'] = `2020ss`,
        ['shop'] = 'pdm',
    },
    ['camrs17'] = {
        ['name'] = '2017 Chevrolet Camaro RS',
        ['brand'] = 'chevrolet',
        ['model'] = 'camrs17',
        ['price'] = 12000,
        ['category'] = 'chevrolet',
        ['hash'] = `camrs17`,
        ['shop'] = 'pdm',
    },
    ['tahoe21'] = {
        ['name'] = '2021 Chevrolet Tahoe RST',
        ['brand'] = 'chevrolet',
        ['model'] = 'tahoe21',
        ['price'] = 45000,
        ['category'] = 'chevrolet',
        ['hash'] = `tahoe21`,
        ['shop'] = 'pdm',
    },
    ['corvettec5z06'] = {
        ['name'] = 'Chevrolet Corvette C5 Z06',
        ['brand'] = 'chevrolet',
        ['model'] = 'corvettec5z06',
        ['price'] = 32000,
        ['category'] = 'chevrolet',
        ['hash'] = `corvettec5z06`,
        ['shop'] = 'pdm',
    },
    ['czr1'] = {
        ['name'] = '2009 Chevrolet Corvette ZR1',
        ['brand'] = 'chevrolet',
        ['model'] = 'czr1',
        ['price'] = 19000,
        ['category'] = 'chevrolet',
        ['hash'] = `czr1`,
        ['shop'] = 'pdm',
    },
    ['c7'] = {
        ['name'] = '2014 Chevrolet Corvette C7 Stingray',
        ['brand'] = 'chevrolet',
        ['model'] = 'c7',
        ['price'] = 29000,
        ['category'] = 'chevrolet',
        ['hash'] = `c7`,
        ['shop'] = 'pdm',
    },
    ['c8'] = {
        ['name'] = '2020 Chevrolet Corvette C8',
        ['brand'] = 'chevrolet',
        ['model'] = 'c8',
        ['price'] = 29000,
        ['category'] = 'chevrolet',
        ['hash'] = `c8`,
        ['shop'] = 'pdm',
    },
    ['16charger'] = {
        ['name'] = '2016 Dodge Charger',
        ['brand'] = 'dodge',
        ['model'] = '16charger',
        ['price'] = 45000,
        ['category'] = 'dodge',
        ['hash'] = `16charger`,
        ['shop'] = 'pdm',
    },
    ['demon'] = {
        ['name'] = '2018 Dodge Challenger SRT Demon',
        ['brand'] = 'dodge',
        ['model'] = 'demon',
        ['price'] = 18000,
        ['category'] = 'dodge',
        ['hash'] = `demon`,
        ['shop'] = 'pdm',
    },
    ['488'] = {
        ['name'] = 'Ferrari 488 Spider',
        ['brand'] = 'ferrari',
        ['model'] = '488',
        ['price'] = 10800,
        ['category'] = 'ferrari',
        ['hash'] = `488`,
        ['shop'] = 'pdm',
    },
    ['f430s'] = {
        ['name'] = 'Ferrari F430 Scuderia',
        ['brand'] = 'ferrari',
        ['model'] = 'f430s',
        ['price'] = 14500,
        ['category'] = 'ferrari',
        ['hash'] = `f430s`,
        ['shop'] = 'pdm',
    },
    ['f812'] = {
        ['name'] = '2018 Ferrari 812 Superfast',
        ['brand'] = 'ferrari',
        ['model'] = 'f812',
        ['price'] = 5500,
        ['category'] = 'ferrari',
        ['hash'] = `f812`,
        ['shop'] = 'pdm',
    },
    ['fct'] = {
        ['name'] = '2015 Ferrari California T',
        ['brand'] = 'ferrari',
        ['model'] = 'fct',
        ['price'] = 55000,
        ['category'] = 'ferrari',
        ['hash'] = `fct`,
        ['shop'] = 'pdm',
    },
    ['fxxk'] = {
        ['name'] = 'Ferrari FXX-K Hybrid Hypercar',
        ['brand'] = 'ferrari',
        ['model'] = 'fxxk',
        ['price'] = 8500,
        ['category'] = 'ferrari',
        ['hash'] = `fxxk`,
        ['shop'] = 'pdm',
    },
    ['laferrari'] = {
        ['name'] = '2015 Ferrari LaFerrari',
        ['brand'] = 'ferrari',
        ['model'] = 'laferrari',
        ['price'] = 12000,
        ['category'] = 'ferrari',
        ['hash'] = `laferrari`,
        ['shop'] = 'pdm',
    },
    ['mig'] = {
        ['name'] = 'Ferrari Enzo',
        ['brand'] = 'ferrari',
        ['model'] = 'mig',
        ['price'] = 6500,
        ['category'] = 'ferrari',
        ['hash'] = `mig`,
        ['shop'] = 'pdm',
    },
    ['yFe458i1'] = {
        ['name'] = '458 Italia',
        ['brand'] = 'ferrari',
        ['model'] = 'yFe458i1',
        ['price'] = 7500,
        ['category'] = 'ferrari',
        ['hash'] = `yFe458i1`,
        ['shop'] = 'pdm',
    },
    ['yFe458i2'] = {
        ['name'] = '458 Speciale',
        ['brand'] = 'ferrari',
        ['model'] = 'yFe458i2',
        ['price'] = 8000,
        ['category'] = 'ferrari',
        ['hash'] = `yFe458i2`,
        ['shop'] = 'pdm',
    },
    ['yFe458s1'] = {
        ['name'] = '458 Spider',
        ['brand'] = 'ferrari',
        ['model'] = 'yFe458s1',
        ['price'] = 14000,
        ['category'] = 'ferrari',
        ['hash'] = `yFe458s1`,
        ['shop'] = 'pdm',
    },
    ['yFe458s1X'] = {
        ['name'] = '458 Spider',
        ['brand'] = 'ferrari',
        ['model'] = 'yFe458s1X',
        ['price'] = 14000,
        ['category'] = 'ferrari',
        ['hash'] = `yFe458s1X`,
        ['shop'] = 'pdm',
    },
    ['yFe458s2'] = {
        ['name'] = '458 Speciale Aperta',
        ['brand'] = 'ferrari',
        ['model'] = 'yFe458s2',
        ['price'] = 5000,
        ['category'] = 'ferrari',
        ['hash'] = `yFe458s2`,
        ['shop'] = 'pdm',
    },
    ['yFe458s2X'] = {
        ['name'] = '458 Speciale Aperta',
        ['brand'] = 'ferrari',
        ['model'] = 'yFe458s2X',
        ['price'] = 5000,
        ['category'] = 'ferrari',
        ['hash'] = `yFe458s2X`,
        ['shop'] = 'pdm',
    },
    ['yFeF12A'] = {
        ['name'] = 'Ferrari F60 America',
        ['brand'] = 'ferrari',
        ['model'] = 'yFeF12A',
        ['price'] = 25000,
        ['category'] = 'ferrari',
        ['hash'] = `yFeF12A`,
        ['shop'] = 'pdm',
    },
    ['yFeF12T'] = {
        ['name'] = 'Ferrari F12 TRS Roadster',
        ['brand'] = 'ferrari',
        ['model'] = 'yFeF12T',
        ['price'] = 90000,
        ['category'] = 'ferrari',
        ['hash'] = `yFeF12T`,
        ['shop'] = 'pdm',
    },
    ['f15078'] = {
        ['name'] = '1978 Ford F150 XLT Ranger',
        ['brand'] = 'ford',
        ['model'] = 'f15078',
        ['price'] = 130000,
        ['category'] = 'ford',
        ['hash'] = `f15078`,
        ['shop'] = 'pdm',
    },
    ['f150'] = {
        ['name'] = '2012 Ford F150 SVT Raptor R',
        ['brand'] = 'ford',
        ['model'] = 'f150',
        ['price'] = 130000,
        ['category'] = 'ford',
        ['hash'] = `f150`,
        ['shop'] = 'pdm',
    },
    ['fgt'] = {
        ['name'] = '2005 Ford GT',
        ['brand'] = 'ford',
        ['model'] = 'fgt',
        ['price'] = 30000,
        ['category'] = 'ford',
        ['hash'] = `fgt`,
        ['shop'] = 'pdm',
    },
    ['gt17'] = {
        ['name'] = '2017 Ford GT',
        ['brand'] = 'ford',
        ['model'] = 'gt17',
        ['price'] = 4000,
        ['category'] = 'ford',
        ['hash'] = `gt17`,
        ['shop'] = 'pdm',
    },
    ['raptor2017'] = {
        ['name'] = '2017 Ford Raptor',
        ['brand'] = 'ford',
        ['model'] = 'raptor2017',
        ['price'] = 40000,
        ['category'] = 'ford',
        ['hash'] = `raptor2017`,
        ['shop'] = 'pdm',
    },
    ['wildtrak'] = {
        ['name'] = '2021 Ford Bronco Wildtrak',
        ['brand'] = 'ford',
        ['model'] = 'wildtrak',
        ['price'] = 60000,
        ['category'] = 'ford',
        ['hash'] = `wildtrak`,
        ['shop'] = 'pdm',
    },
    ['honcrx91'] = {
        ['name'] = 'Honda CRX SiR 1991',
        ['brand'] = 'honda',
        ['model'] = 'honcrx91',
        ['price'] = 55000,
        ['category'] = 'honda',
        ['hash'] = `honcrx91`,
        ['shop'] = 'pdm',
    },
    ['na1'] = {
        ['name'] = '1992 Honda NSX-R NA1',
        ['brand'] = 'honda',
        ['model'] = 'na1',
        ['price'] = 70000,
        ['category'] = 'honda',
        ['hash'] = `na1`,
        ['shop'] = 'pdm',
    },
    ['ap2'] = {
        ['name'] = 'Honda S2000 AP2',
        ['brand'] = 'honda',
        ['model'] = 'ap2',
        ['price'] = 45000,
        ['category'] = 'honda',
        ['hash'] = `ap2`,
        ['shop'] = 'pdm',
    },
    ['fk8'] = {
        ['name'] = '2018 Honda Civic Type-R FK8',
        ['brand'] = 'honda',
        ['model'] = 'fk8',
        ['price'] = 60000,
        ['category'] = 'honda',
        ['hash'] = `fk8`,
        ['shop'] = 'pdm',
    },
    ['17civict'] = {
        ['name'] = '2017 Honda Civic Touring',
        ['brand'] = 'honda',
        ['model'] = '17civict',
        ['price'] = 60000,
        ['category'] = 'honda',
        ['hash'] = `17civict`,
        ['shop'] = 'pdm',
    },
    ['it18'] = {
        ['name'] = '2017 Italdesign Zerouno',
        ['brand'] = 'italdesign',
        ['model'] = 'it18',
        ['price'] = 17000,
        ['category'] = 'italdesign',
        ['hash'] = `it18`,
        ['shop'] = 'pdm',
    },
    ['fpacehm'] = {
        ['name'] = 'Jaguar F-pace 2017 Hamann Edition',
        ['brand'] = 'jaguar',
        ['model'] = 'fpacehm',
        ['price'] = 50000,
        ['category'] = 'jaguar',
        ['hash'] = `fpacehm`,
        ['shop'] = 'pdm',
    },
    ['jeep2012'] = {
        ['name'] = '2012 Jeep Wrangler',
        ['brand'] = 'jeep',
        ['model'] = 'jeep2012',
        ['price'] = 47500,
        ['category'] = 'jeep',
        ['hash'] = `jeep2012`,
        ['shop'] = 'pdm',
    },
    ['jeepreneg'] = {
        ['name'] = 'Jeep Renegade',
        ['brand'] = 'jeep',
        ['model'] = 'jeepreneg',
        ['price'] = 40000,
        ['category'] = 'jeep',
        ['hash'] = `jeepreneg`,
        ['shop'] = 'pdm',
    },
    ['srt8'] = {
        ['name'] = '2015 Jeep SRT-8',
        ['brand'] = 'jeep',
        ['model'] = 'srt8',
        ['price'] = 35000,
        ['category'] = 'jeep',
        ['hash'] = `srt8`,
        ['shop'] = 'pdm',
    },
    ['trhawk'] = {
        ['name'] = '2018 Jeep Grand Cherokee',
        ['brand'] = 'jeep',
        ['model'] = 'trhawk',
        ['price'] = 16000,
        ['category'] = 'jeep',
        ['hash'] = `trhawk`,
        ['shop'] = 'pdm',
    },
    ['regera'] = {
        ['name'] = 'Koenigsegg Regera',
        ['brand'] = 'koenigsegg',
        ['model'] = 'regera',
        ['price'] = 55000,
        ['category'] = 'koenigsegg',
        ['hash'] = `regera`,
        ['shop'] = 'pdm',
    },
    ['huracanst'] = {
        ['name'] = 'Lamborghini Huracan Super Trofeo',
        ['brand'] = 'lamborghini',
        ['model'] = 'huracanst',
        ['price'] = 29000,
        ['category'] = 'lamborghini',
        ['hash'] = `huracanst`,
        ['shop'] = 'pdm',
    },
    ['lambose'] = {
        ['name'] = 'Lamborghini Sesto Elemento',
        ['brand'] = 'lamborghini',
        ['model'] = 'lambose',
        ['price'] = 45000,
        ['category'] = 'lamborghini',
        ['hash'] = `lambose`,
        ['shop'] = 'pdm',
    },
    ['lp700r'] = {
        ['name'] = '2013 Lamborghini Aventador LP700-4 Roadster',
        ['brand'] = 'lamborghini',
        ['model'] = 'lp700r',
        ['price'] = 32000,
        ['category'] = 'lamborghini',
        ['hash'] = `lp700r`,
        ['shop'] = 'pdm',
    },
    ['svj63'] = {
        ['name'] = 'Lamborghini Aventador SVJ',
        ['brand'] = 'lamborghini',
        ['model'] = 'svj63',
        ['price'] = 62000,
        ['category'] = 'lamborghini',
        ['hash'] = `svj63`,
        ['shop'] = 'pdm',
    },
    ['urus'] = {
        ['name'] = 'Lamborghini Urus',
        ['brand'] = 'lamborghini',
        ['model'] = 'urus',
        ['price'] = 85000,
        ['category'] = 'lamborghini',
        ['hash'] = `urus`,
        ['shop'] = 'pdm',
    },
    ['veneno'] = {
        ['name'] = 'Lamborghini Veneno',
        ['brand'] = 'lamborghini',
        ['model'] = 'veneno',
        ['price'] = 155000,
        ['category'] = 'lamborghini',
        ['hash'] = `veneno`,
        ['shop'] = 'pdm',
    },
    ['gs350'] = {
        ['name'] = 'Lexus GS 350',
        ['brand'] = 'lexus',
        ['model'] = 'gs350',
        ['price'] = 30000,
        ['category'] = 'lexus',
        ['hash'] = `gs350`,
        ['shop'] = 'pdm',
    },
    ['rcf'] = {
        ['name'] = '2015 Lexus RCF',
        ['brand'] = 'lexus',
        ['model'] = 'rcf',
        ['price'] = 12800,
        ['category'] = 'lexus',
        ['hash'] = `rcf`,
        ['shop'] = 'pdm',
    },
    ['lrrr'] = {
        ['name'] = '1973 Land Rover Range Rover',
        ['brand'] = 'landrover',
        ['model'] = 'lrrr',
        ['price'] = 55000,
        ['category'] = 'landrover',
        ['hash'] = `lrrr`,
        ['shop'] = 'pdm',
    },
    ['esprit02'] = {
        ['name'] = '2002 Lotus Esprit V8',
        ['brand'] = 'lotus',
        ['model'] = 'esprit02',
        ['price'] = 20000,
        ['category'] = 'lotus',
        ['hash'] = `esprit02`,
        ['shop'] = 'pdm',
    },
    ['regalia'] = {
        ['name'] = 'Quartz Regalia 723',
        ['brand'] = 'quartz',
        ['model'] = 'regalia',
        ['price'] = 80000,
        ['category'] = 'quartz',
        ['hash'] = `regalia`,
        ['shop'] = 'pdm',
    },
    ['levante'] = {
        ['name'] = 'Maserati Levante',
        ['brand'] = 'maserati',
        ['model'] = 'levante',
        ['price'] = 75000,
        ['category'] = 'maserati',
        ['hash'] = `levante`,
        ['shop'] = 'pdm',
    },
    ['84rx7k'] = {
        ['name'] = '1984 Mazda RX-7 Stanced Version',
        ['brand'] = 'mazda',
        ['model'] = '84rx7k',
        ['price'] = 65000,
        ['category'] = 'mazda',
        ['hash'] = `84rx7k`,
        ['shop'] = 'pdm',
    },
    ['dragfd'] = {
        ['name'] = '2002 Mazda RX-7 FD Drag',
        ['brand'] = 'mazda',
        ['model'] = 'dragfd',
        ['price'] = 220000,
        ['category'] = 'mazda',
        ['hash'] = `dragfd`,
        ['shop'] = 'pdm',
    },
    ['fc3s'] = {
        ['name'] = 'Mazda RX7 FC3S',
        ['brand'] = 'mazda',
        ['model'] = 'fc3s',
        ['price'] = 12000,
        ['category'] = 'mazda',
        ['hash'] = `fc3s`,
        ['shop'] = 'pdm',
    },
    ['majfd'] = {
        ['name'] = 'Mazda RX-7 FD',
        ['brand'] = 'mazda',
        ['model'] = 'majfd',
        ['price'] = 16000,
        ['category'] = 'mazda',
        ['hash'] = `majfd`,
        ['shop'] = 'pdm',
    },
    ['miata3'] = {
        ['name'] = '1989 Mazda Miata NA',
        ['brand'] = 'mazda',
        ['model'] = 'miata3',
        ['price'] = 6500,
        ['category'] = 'mazda',
        ['hash'] = `miata3`,
        ['shop'] = 'pdm',
    },
    ['na6'] = {
        ['name'] = 'Mazda MX-5 Miata NA6C',
        ['brand'] = 'mazda',
        ['model'] = 'na6',
        ['price'] = 8500,
        ['category'] = 'mazda',
        ['hash'] = `na6`,
        ['shop'] = 'pdm',
    },
    ['mcst'] = {
        ['name'] = '2020 McLaren Speedtail',
        ['brand'] = 'mclaren',
        ['model'] = 'mcst',
        ['price'] = 35000,
        ['category'] = 'mclaren',
        ['hash'] = `mcst`,
        ['shop'] = 'pdm',
    },
    ['amggtrr20'] = {
        ['name'] = '2020 Mercedes-Benz AMG GT-R Roadster',
        ['brand'] = 'mercedes',
        ['model'] = 'amggtrr20',
        ['price'] = 60000,
        ['category'] = 'mercedesbenz',
        ['hash'] = `amggtrr20`,
        ['shop'] = 'pdm',
    },
    ['c6320'] = {
        ['name'] = '2020 Mercedes-AMG C63s',
        ['brand'] = 'mercedes',
        ['model'] = 'c6320',
        ['price'] = 80000,
        ['category'] = 'mercedes',
        ['hash'] = `c6320`,
        ['shop'] = 'pdm',
    },
    ['G65'] = {
        ['name'] = '2013 Mercedes-Benz G65 AMG',
        ['brand'] = 'mercedes',
        ['model'] = 'G65',
        ['price'] = 55000,
        ['category'] = 'mercedes',
        ['hash'] = `G65`,
        ['shop'] = 'pdm',
    },
    ['e400'] = {
        ['name'] = '2019 Mercedes-Benz E400 Coupe 4matic C238',
        ['brand'] = 'mercedes',
        ['model'] = 'e400',
        ['price'] = 32000,
        ['category'] = 'mercedes',
        ['hash'] = `e400`,
        ['shop'] = 'pdm',
    },
    ['gl63'] = {
        ['name'] = 'Mercedes-Benz GL63 AMG',
        ['brand'] = 'mercedes',
        ['model'] = 'gl63',
        ['price'] = 40000,
        ['category'] = 'mercedes',
        ['hash'] = `gl63`,
        ['shop'] = 'pdm',
    },
    ['mbc63'] = {
        ['name'] = '2012 Mercedes-Benz C63 AMG Coupe Black Series',
        ['brand'] = 'mercedes',
        ['model'] = 'mbc63',
        ['price'] = 42000,
        ['category'] = 'mercedes',
        ['hash'] = `mbc63`,
        ['shop'] = 'pdm',
    },
    ['s500w222'] = {
        ['name'] = '2014 Mercedes-Benz S500 W222',
        ['brand'] = 'mercedes',
        ['model'] = 's500w222',
        ['price'] = 55000,
        ['category'] = 'mercedes',
        ['hash'] = `s500w222`,
        ['shop'] = 'pdm',
    },
    ['sl500'] = {
        ['name'] = '1995 Mercedes-Benz SL500',
        ['brand'] = 'mercedes',
        ['model'] = 'sl500',
        ['price'] = 38000,
        ['category'] = 'mercedes',
        ['hash'] = `sl500`,
        ['shop'] = 'pdm',
    },
    ['v250'] = {
        ['name'] = 'Mercedes-Benz V-class 250 Bluetec LWB',
        ['brand'] = 'mercedes',
        ['model'] = 'v250',
        ['price'] = 35000,
        ['category'] = 'mercedes',
        ['hash'] = `v250`,
        ['shop'] = 'pdm',
    },
    ['cp9a'] = {
        ['name'] = 'Mitsubishi Lancer Evo VI T.M.E CP9A',
        ['brand'] = 'mitsubishi',
        ['model'] = 'cp9a',
        ['price'] = 32000,
        ['category'] = 'mitsubishi',
        ['hash'] = `cp9a`,
        ['shop'] = 'pdm',
    },
    ['fto'] = {
        ['name'] = 'Mitsubishi FTO GP Version-R',
        ['brand'] = 'mitsubishi',
        ['model'] = 'fto',
        ['price'] = 40000,
        ['category'] = 'mitsubishi',
        ['hash'] = `fto`,
        ['shop'] = 'pdm',
    },
    ['180sx'] = {
        ['name'] = 'Nissan 180SX Type-X',
        ['brand'] = 'nissan',
        ['model'] = '180sx',
        ['price'] = 95000,
        ['category'] = 'nissan',
        ['hash'] = `180sx`,
        ['shop'] = 'pdm',
    },
    ['gtr'] = {
        ['name'] = '2017 Nissan GTR',
        ['brand'] = 'nissan',
        ['model'] = 'gtr',
        ['price'] = 125000,
        ['category'] = 'nissan',
        ['hash'] = `gtr`,
        ['shop'] = 'pdm',
    },
    ['gtrc'] = {
        ['name'] = '2017 R35 Nissan GTR Convertible',
        ['brand'] = 'nissan',
        ['model'] = 'gtrc',
        ['price'] = 36000,
        ['category'] = 'nissan',
        ['hash'] = `gtrc`,
        ['shop'] = 'pdm',
    },
    ['maj350'] = {
        ['name'] = 'Nissan Fairlady Z Z33',
        ['brand'] = 'nissan',
        ['model'] = 'maj350',
        ['price'] = 45000,
        ['category'] = 'nissan',
        ['hash'] = `maj350`,
        ['shop'] = 'pdm',
    },
    ['nis15'] = {
        ['name'] = 'Nissan Silvia S15 Spec-R',
        ['brand'] = 'nissan',
        ['model'] = 'nis15',
        ['price'] = 65000,
        ['category'] = 'nissan',
        ['hash'] = `nis15`,
        ['shop'] = 'pdm',
    },
    ['nissantitan17'] = {
        ['name'] = '2017 Nissan Titan Warrior',
        ['brand'] = 'nissan',
        ['model'] = 'nissantitan17',
        ['price'] = 80000,
        ['category'] = 'nissan',
        ['hash'] = `nissantitan17`,
        ['shop'] = 'pdm',
    },
    ['ns350'] = {
        ['name'] = 'Nissan 350z Stardast',
        ['brand'] = 'nissan',
        ['model'] = 'ns350',
        ['price'] = 60000,
        ['category'] = 'nissan',
        ['hash'] = `ns350`,
        ['shop'] = 'pdm',
    },
    ['nzp'] = {
        ['name'] = 'Nissan 370z Pandem',
        ['brand'] = 'nissan',
        ['model'] = 'nzp',
        ['price'] = 70000,
        ['category'] = 'nissan',
        ['hash'] = `nzp`,
        ['shop'] = 'pdm',
    },
    ['s14'] = {
        ['name'] = '1998 Nissan Silvia K',
        ['brand'] = 'nissan',
        ['model'] = 's14',
        ['price'] = 55000,
        ['category'] = 'nissan',
        ['hash'] = `s14`,
        ['shop'] = 'pdm',
    },
    ['Safari97'] = {
        ['name'] = '1997 Nissan Patrol Super Safari Y60',
        ['brand'] = 'nissan',
        ['model'] = 'Safari97',
        ['price'] = 12000,
        ['category'] = 'nissan',
        ['hash'] = `Safari97`,
        ['shop'] = 'pdm',
    },
    ['skyline'] = {
        ['name'] = 'Nissan Skyline GT-R BNR34',
        ['brand'] = 'nissan',
        ['model'] = 'skyline',
        ['price'] = 20000,
        ['category'] = 'nissan',
        ['hash'] = `skyline`,
        ['shop'] = 'pdm',
    },
    ['z32'] = {
        ['name'] = 'Nissan 300ZX Z32',
        ['brand'] = 'nissan',
        ['model'] = 'z32',
        ['price'] = 75000,
        ['category'] = 'nissan',
        ['hash'] = `z32`,
        ['shop'] = 'pdm',
    },
    ['maj935'] = {
        ['name'] = '1978 Porsche 935 Moby Dick',
        ['brand'] = 'porsche',
        ['model'] = 'maj935',
        ['price'] = 65000,
        ['category'] = 'porsche',
        ['hash'] = `maj935`,
        ['shop'] = 'pdm',
    },
    ['pcs18'] = {
        ['name'] = '2018 Porsche Cayenne S',
        ['brand'] = 'porsche',
        ['model'] = 'pcs18',
        ['price'] = 65000,
        ['category'] = 'porsche',
        ['hash'] = `pcs18`,
        ['shop'] = 'pdm',
    },
    ['718caymans'] = {
        ['name'] = 'Porsche 718 Cayman S',
        ['brand'] = 'porsche',
        ['model'] = '718caymans',
        ['price'] = 80000,
        ['category'] = 'porsche',
        ['hash'] = `718caymans`,
        ['shop'] = 'pdm',
    },
    ['cgt'] = {
        ['name'] = '2003 Porsche Carrera GT 980',
        ['brand'] = 'porsche',
        ['model'] = 'cgt',
        ['price'] = 38500,
        ['category'] = 'porsche',
        ['hash'] = `cgt`,
        ['shop'] = 'pdm',
    },
    ['pm19'] = {
        ['name'] = '2019 Porsche Macan Turbo',
        ['brand'] = 'porsche',
        ['model'] = 'pm19',
        ['price'] = 55000,
        ['category'] = 'porsche',
        ['hash'] = `pm19`,
        ['shop'] = 'pdm',
    },
    ['taycan'] = {
        ['name'] = '2020 Porsche Taycan Turbo S',
        ['brand'] = 'porsche',
        ['model'] = 'taycan',
        ['price'] = 45000,
        ['category'] = 'porsche',
        ['hash'] = `taycan`,
        ['shop'] = 'pdm',
    },
    ['rrevoque'] = {
        ['name'] = 'Range Rover Evoque',
        ['brand'] = 'rangerover',
        ['model'] = 'rrevoque',
        ['price'] = 40000,
        ['category'] = 'rangerover',
        ['hash'] = `rrevoque`,
        ['shop'] = 'pdm',
    },
    ['rsvr16'] = {
        ['name'] = '2016 Range Rover Sport SVR',
        ['brand'] = 'rangerover',
        ['model'] = 'rsvr16',
        ['price'] = 135000,
        ['category'] = 'rangerover',
        ['hash'] = `rsvr16`,
        ['shop'] = 'pdm',
    },
    ['wraith'] = {
        ['name'] = 'Rolls-Royce Wraith',
        ['brand'] = 'rollsroyce',
        ['model'] = 'wraith',
        ['price'] = 30000,
        ['category'] = 'rollsroyce',
        ['hash'] = `wraith`,
        ['shop'] = 'pdm',
    },
    ['rculi'] = {
        ['name'] = 'Rolls Royce Cullinan',
        ['brand'] = 'rollsroyce',
        ['model'] = 'rculi',
        ['price'] = 40000,
        ['category'] = 'rollsroyce',
        ['hash'] = `rculi`,
        ['shop'] = 'pdm',
    },
    ['rrphantom'] = {
        ['name'] = '2018 Rolls-Royce Phantom VIII',
        ['brand'] = 'rollsroyce',
        ['model'] = 'rrphantom',
        ['price'] = 70000,
        ['category'] = 'rollsroyce',
        ['hash'] = `rrphantom`,
        ['shop'] = 'pdm',
    },
    ['subisti08'] = {
        ['name'] = '2008 Subaru WRX STi',
        ['brand'] = 'subaru',
        ['model'] = 'subisti08',
        ['price'] = 65000,
        ['category'] = 'subaru',
        ['hash'] = `subisti08`,
        ['shop'] = 'pdm',
    },
    ['subwrx'] = {
        ['name'] = '2004 Subaru Impreza WRX STI',
        ['brand'] = 'subaru',
        ['model'] = 'subwrx',
        ['price'] = 130000,
        ['category'] = 'subaru',
        ['hash'] = `subwrx`,
        ['shop'] = 'pdm',
    },
    ['svx'] = {
        ['name'] = '1996 Subaru Alcyone SVX',
        ['brand'] = 'subaru',
        ['model'] = 'svx',
        ['price'] = 35000,
        ['category'] = 'subaru',
        ['hash'] = `svx`,
        ['shop'] = 'pdm',
    },
    ['vxr'] = {
        ['name'] = '2016 Toyota Land Cruiser VXR',
        ['brand'] = 'toyota',
        ['model'] = 'vxr',
        ['price'] = 900000,
        ['category'] = 'toyota',
        ['hash'] = `vxr`,
        ['shop'] = 'pdm',
    },
    ['mk2100'] = {
        ['name'] = 'Toyota Mark II JZX100',
        ['brand'] = 'toyota',
        ['model'] = 'mk2100',
        ['price'] = 90000,
        ['category'] = 'toyota',
        ['hash'] = `mk2100`,
        ['shop'] = 'pdm',
    },
    ['a80'] = {
        ['name'] = 'Toyota Supra',
        ['brand'] = 'toyota',
        ['model'] = 'a80',
        ['price'] = 90000,
        ['category'] = 'toyota',
        ['hash'] = `a80`,
        ['shop'] = 'pdm',
    },
    ['golfgti7'] = {
        ['name'] = '2015 Volkswagen Golf GTI MK7',
        ['brand'] = 'volkswagen',
        ['model'] = 'golfgti7',
        ['price'] = 375000,
        ['category'] = 'volkswagen',
        ['hash'] = `golfgti7`,
        ['shop'] = 'pdm',
    },
    ['xc90'] = {
        ['name'] = 'Volvo XC90 T8',
        ['brand'] = 'volvo',
        ['model'] = 'xc90',
        ['price'] = 425000,
        ['category'] = 'volvo',
        ['hash'] = `xc90`,
        ['shop'] = 'pdm',
    },
    ['wmfenyr'] = {
        ['name'] = 'W-Motors Fenyr Supersport',
        ['brand'] = 'wmotors',
        ['model'] = 'wmfenyr',
        ['price'] = 220000,
        ['category'] = 'wmotors',
        ['hash'] = `wmfenyr`,
        ['shop'] = 'pdm',
    },
    ['lykan'] = {
        ['name'] = 'W-Motors Lykan HyperSport',
        ['brand'] = 'wmotors',
        ['model'] = 'lykan',
        ['price'] = 185000,
        ['category'] = 'wmotors',
        ['hash'] = `lykan`,
        ['shop'] = 'pdm',
    },
